@ version BARC221740652101
[HKEY_LOCAL_MACHINE\SOFTWARE\Gemalto\eSigner]
"GUI.MinHeight"=dword:000001E0
"GUI.MinWidth"=dword:000001E0
"GUI.ConfigIHMDir"="eSigner4Path"
"PKCS11LibraryName"="P11Path"
"PINTriesLeft.Display.enable"=dword:00000001
"ISPI.mode.support"=dword:00000001
"CustomLogo.Stretch"=dword:00000001
"RootCerts.source"=dword:0000000f
"CustomLogo.File"="gemaltoLogo.png"
"CustomLogo.TranspColor"="000000"
"CustomLogo.Url"=""
"Sign.CheckCertificateChain"=dword:00000001
"Sign.CertFilter.ICN"=""
"Sign.CertFilter.KU"="192:0"
"Sign.HashMechanismList"="sha256,sha1"
"Sign.Swys.ReaderFallback"=dword:00000001
"Pkcs11.forcePin"=dword:00000000
"Pin.MinimumSize"=dword:00000006
"Pin.MaximumSize"=dword:00000008
"Pin.EntryMode"=dword:00000002
"Certificate.Pin.Request"=dword:00000000
"ExternalData.View.Mode"=dword:00000003
"Sign.Save.Button"=dword:00000001
"Identrust.Version"="3.2"

@ LargeData.MultiPageDisplay enables/disables MultiPageMode (1/0) default 1
"LargeData.MultiPageDisplay"=dword:00000001

@ Text.Plain.MaxGridSize: maximum character matrix that eSigner will accept
@     to display as a single WYSIWYS window, default value=360000 (hexa = 00057E40).
"Text.Plain.MaxGridSize"=dword:00057E40

[Signature]
ExcludedKeys=GUI.ConfigIHMDir,PKCS11LibraryName
Rnd=134EF119CD031D5BBFF7DC927C054E89
Signature=A91270DC79CDFC1009C8C7CFAF942B1F487FBE43C4B0151DC476CAC52CF312923B612B5118B12F633FB34E4ACAB3D64616852FEE7A48AC6C044C3FBFA3A375B9
